# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Felix
subtitle: Viva La Vida
description: 周宇峰的博客
keywords: 周宇峰,zyf,zhouyufeng,yfzhou,博客,yf.Zhou,felix,Felix
author: Felix
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://yfzhou.coding.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: static/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
#index_generator:
#  path: ''
#  per_page: 10
#  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页配置
# ---------------下面选项需要对应插件的支持---------------
# npm install hexo-generator-index --save
# npm install hexo-generator-archive --save
# npm install hexo-generator-category --save
# npm install hexo-generator-tag --save
## Set per_page to 0 to disable pagination
#每页显示的文章量 
#per_page: 20
#首页的分页设置
index_generator:
  per_page: 10
#归档页的分页设置
archive_generator:
  per_page: 30
  yearly: true
  monthly: true
#标签页的分页设置
tag_generator:
  per_page: 20

#分页路径，在public中可以看到
#pagination_dir: page


# Extensions 拓展插件配置
## Plugins: https://hexo.io/plugins/
plugins: 
sitemap: 
  path: sitemap.xml


# 配置RSS
feed: 
  #feed 类型 (atom/rss2)
  type: atom   
  #rss 路径
  path: atom.xml  
  #在 rss 中最多生成的文章数(0显示所有)
  limit: 0

# emoji 支持
githubEmojis:
  enable: true
  idName: github-emoji
  unicode: false
  styles:
  localEmojis:


# 自定义站点内容搜索
# 需要先安装插件：
# npm install hexo-generator-search --save
search:
  path: search.xml
  # 如只想索引文章，可设置为post
  field: all 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  #repo: git@github.com:542869246/542869246.github.io.git
 # branch: master
  repo:
    coding: git@git.coding.net:yfzhou/yfzhou.git,master
    github: git@github.com:542869246/542869246.github.io.git,master
- type: baidu_url_submitter
- type: leancloud_counter_security_sync




# 百度分享功能
baidushare: true 

# Algolia Search API Key
algolia:
  applicationID: '5GWESN2MHV'
  apiKey: '756045653a25072015750606fb533a33'
  adminApiKey: 'ae2151e8f81a0c2d6b89fb4d1501e48d'
  indexName: 'hexo blog'
  chunkSize: 5000

baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: yfzhou.coding.me # 在百度站长平台中注册的域名
  token: HFkjiVFYGbTik7jc # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里
 
 
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  
leancloud_counter_security:
  enable_sync: true
  app_id: "4DkhRkq5CadWFisToA3zFrop-gzGzoHsz"
  app_key: "xihAA2ETGTdekJFloguCmmgq"
  username: "542869246"
  password: "542869246zyf"